# Generated by Django 2.2.2 on 2019-06-22 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogposts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='latestpost',
            name='timestamp',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='popular',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
