# Generated by Django 2.2.2 on 2019-06-22 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogposts', '0002_auto_20190622_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='latestpost',
            name='timestamp',
            field=models.DateTimeField(max_length=50),
        ),
    ]
